# Generated by Django 4.2.4 on 2023-08-23 21:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coursename', models.CharField(max_length=100)),
                ('coursedetails', models.TextField(blank=True, null=True)),
                ('coursefees', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='studentsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=50)),
                ('lastname', models.CharField(max_length=50)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(max_length=20)),
                ('phoneno', models.IntegerField()),
                ('emailid', models.EmailField(max_length=254)),
                ('address', models.TextField(blank=True, null=True)),
                ('joiningdate', models.DateField()),
                ('completiondate', models.DateField()),
                ('coursefees', models.IntegerField()),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('coursename', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp.courses')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
