# Generated by Django 4.2.4 on 2023-08-23 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentsmodel',
            name='feespaid',
            field=models.IntegerField(default=0),
        ),
    ]
