# Generated by Django 4.2.4 on 2023-08-30 02:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_pdffile'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PDFFile',
            new_name='SyllabusPDFFile',
        ),
    ]
