# Generated by Django 4.2.4 on 2023-08-30 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_syllabusdownloadrecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='courses',
            name='file_path',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
