# Generated by Django 4.2.4 on 2023-09-01 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_alter_studentsmodel_phoneno'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentsmodel',
            name='exam_date',
            field=models.BooleanField(default=False),
        ),
    ]
