# Generated by Django 4.2.4 on 2023-09-01 03:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0012_remove_studentsmodel_exam_given_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="studentsmodel",
            name="exam_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
