# Generated by Django 4.2.4 on 2023-09-01 03:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_studentsmodel_exam_given_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentsmodel',
            old_name='exam_date',
            new_name='theexam_date',
        ),
    ]
