# Generated by Django 4.2.4 on 2023-09-01 03:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_rename_exam_date_studentsmodel_theexam_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentsmodel',
            name='theexam_date',
        ),
    ]
