# Generated by Django 4.2.4 on 2023-09-01 03:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0016_studentsmodel_exam_date_studentsmodel_exam_given'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentsmodel',
            name='exam_date',
        ),
        migrations.RemoveField(
            model_name='studentsmodel',
            name='exam_given',
        ),
    ]
