# Generated by Django 4.2.4 on 2023-09-06 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0020_studentremarks'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentsmodel',
            name='rollno',
            field=models.IntegerField(default=0),
        ),
    ]
