# Generated by Django 4.2.4 on 2023-09-06 22:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0021_studentsmodel_rollno'),
    ]

    operations = [
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_day', models.CharField(choices=[('MWF', 'Monday, Wednesday, Friday'), ('TTS', 'Tuesday, Thursday, Saturday'), ('SUN', 'Sunday')], max_length=3)),
                ('batch_time', models.CharField(choices=[('7PM-8:30PM', '7:00 PM - 8:30 PM'), ('8:30PM-10PM', '8:30 PM - 10:00 PM'), ('SUN-10AM-2PM', 'Sunday 10:00 AM - 2:00 PM')], max_length=12)),
            ],
        ),
        migrations.AddField(
            model_name='studentsmodel',
            name='batch_day',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students_with_batch_day', to='myapp.batch'),
        ),
        migrations.AddField(
            model_name='studentsmodel',
            name='batch_time',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students_with_batch_time', to='myapp.batch'),
        ),
    ]
