# Generated by Django 4.2.4 on 2023-09-06 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0022_batch_studentsmodel_batch_day_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batch',
            name='batch_day',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='batch',
            name='batch_time',
            field=models.CharField(max_length=100),
        ),
    ]
