# Generated by Django 4.2.4 on 2023-09-07 00:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0023_alter_batch_batch_day_alter_batch_batch_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='batch',
            old_name='batch_day',
            new_name='batch_and_time',
        ),
        migrations.RemoveField(
            model_name='batch',
            name='batch_time',
        ),
    ]
