# Generated by Django 4.2.4 on 2023-09-07 00:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0024_rename_batch_day_batch_batch_and_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentsmodel',
            name='batch_day',
        ),
        migrations.RemoveField(
            model_name='studentsmodel',
            name='batch_time',
        ),
        migrations.AddField(
            model_name='studentsmodel',
            name='batch_and_time',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp.batch'),
        ),
    ]
