# Generated by Django 4.2.4 on 2023-09-07 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0026_rename_batch_and_time_batch_batch_day_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batch',
            name='batch_time',
            field=models.CharField(blank=True, default='8:30 pm - 10:30 pm', max_length=100, null=True),
        ),
    ]
