# Generated by Django 4.2.4 on 2023-09-07 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0027_alter_batch_batch_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batch',
            name='batch_day',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='batch',
            name='batch_time',
            field=models.CharField(default='8:30 pm - 10:30 pm', max_length=100),
        ),
    ]
