# Generated by Django 4.2.4 on 2023-09-07 00:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0028_alter_batch_batch_day_alter_batch_batch_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentsmodel',
            name='batch_day',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students_with_batch_day', to='myapp.batch'),
        ),
    ]
