# Generated by Django 4.2.4 on 2023-09-07 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0029_alter_studentsmodel_batch_day'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentsmodel',
            name='extendeddate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
