# Generated by Django 4.2.4 on 2023-09-07 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0030_studentsmodel_extendeddate'),
    ]

    operations = [
        migrations.CreateModel(
            name='Enquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=50)),
                ('lastname', models.CharField(max_length=50)),
                ('phoneno', models.BigIntegerField()),
                ('address', models.TextField(blank=True, null=True)),
                ('reference', models.CharField(max_length=50)),
            ],
        ),
    ]
