# Generated by Django 4.2.4 on 2023-09-10 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0033_studentsmodel_initial_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentsmodel',
            name='occupation',
            field=models.CharField(default='Student', max_length=200),
        ),
    ]
