# Generated by Django 4.2.4 on 2023-09-10 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0034_studentsmodel_occupation'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentsmodel',
            name='admissioncancel',
            field=models.BooleanField(default=False),
        ),
    ]
