# Generated by Django 4.2.4 on 2023-09-11 18:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0035_studentsmodel_admissioncancel'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamReports',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_status', models.CharField(default='None', max_length=10)),
                ('theory_marks', models.IntegerField(default='None')),
                ('practical_marks', models.IntegerField(default=None)),
                ('total_marks', models.IntegerField(default=None)),
                ('percentage', models.IntegerField(default=None)),
                ('marksheet_no', models.IntegerField(default=None)),
                ('coursename', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp.courses')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.studentsmodel')),
            ],
        ),
    ]
