# Generated by Django 4.2.4 on 2023-09-20 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0038_alter_examreports_percentage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examreports',
            name='exam_status',
            field=models.BooleanField(default=False),
        ),
    ]
