# Generated by Django 4.2.4 on 2023-09-28 12:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0039_alter_examreports_exam_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phoneno', models.BigIntegerField()),
                ('request_date', models.DateField(auto_now_add=True)),
                ('is_completed', models.BooleanField(default=False)),
                ('change_batch_time', models.BooleanField(default=False)),
                ('extend_batch_time', models.BooleanField(default=False)),
                ('special_batch', models.BooleanField(default=False)),
                ('course_rejoin', models.BooleanField(default=False)),
                ('course_extend', models.BooleanField(default=False)),
                ('course_duration_extend', models.BooleanField(default=False)),
                ('course_break', models.BooleanField(default=False)),
                ('fast_track', models.BooleanField(default=False)),
                ('extra_practice', models.BooleanField(default=False)),
                ('name_correction', models.BooleanField(default=False)),
                ('installment_extend', models.BooleanField(default=False)),
                ('trust_letter', models.BooleanField(default=False)),
                ('duplicate_id', models.BooleanField(default=False)),
                ('duplicate_certificate', models.BooleanField(default=False)),
                ('certificate_marksheet_bypost', models.BooleanField(default=False)),
                ('reissue_book', models.BooleanField(default=False)),
                ('reissue_hall_ticket', models.BooleanField(default=False)),
                ('re_exam', models.BooleanField(default=False)),
                ('mobile_num_change', models.BooleanField(default=False)),
                ('fine_or_penalty_waivedoff', models.BooleanField(default=False)),
                ('cancel_admission', models.BooleanField(default=False)),
                ('other_services', models.BooleanField(default=False)),
                ('request_details', models.TextField(blank=True, default=None, null=True)),
                ('policy_agreement', models.BooleanField(default=False)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.studentsmodel')),
            ],
        ),
    ]
