# Generated by Django 4.2.4 on 2023-09-28 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0040_service'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Service',
            new_name='Services',
        ),
    ]
