# Generated by Django 4.2.4 on 2023-09-28 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0042_services_rollno_services_student_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='services',
            name='student',
        ),
    ]
