# Generated by Django 4.2.4 on 2023-09-28 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0043_remove_services_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='services',
            name='attendance_chart',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='services',
            name='change_faculty',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='services',
            name='holiday_leave',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='services',
            name='recheck_exampaper',
            field=models.BooleanField(default=False),
        ),
    ]
