# Generated by Django 4.2.4 on 2023-09-28 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0044_services_attendance_chart_services_change_faculty_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='services',
            name='coursename',
            field=models.CharField(default='course name', max_length=100),
        ),
    ]
