# Generated by Django 4.2.4 on 2023-11-03 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0048_alter_examreports_marksheet_no_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='examreports',
            name='hallticket_no',
            field=models.IntegerField(default=0),
        ),
    ]
