# Generated by Django 4.2.4 on 2023-11-07 20:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0049_examreports_hallticket_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='services',
            name='student',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.studentsmodel'),
        ),
    ]
