# Generated by Django 4.2.4 on 2023-11-08 20:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0051_alter_services_student'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='services',
            name='student',
        ),
    ]
