# Generated by Django 4.2.4 on 2023-11-08 21:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0052_remove_services_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='services',
            name='student',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp.studentsmodel'),
        ),
    ]
