# Generated by Django 4.2.4 on 2024-01-26 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0053_services_student"),
    ]

    operations = [
        migrations.AddField(
            model_name="studentsmodel",
            name="image",
            field=models.ImageField(
                blank=True,
                default="default-student.png",
                null=True,
                upload_to="student_images/",
            ),
        ),
        migrations.AddField(
            model_name="studentsmodel",
            name="status",
            field=models.CharField(
                choices=[
                    ("active", "Active"),
                    ("pending", "Pending"),
                    ("cancelled", "Cancelled"),
                    ("paused", "Paused"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
    ]
