# Generated by Django 4.2.4 on 2024-01-27 03:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0069_courseimage"),
    ]

    operations = [
        migrations.DeleteModel(
            name="CourseImage",
        ),
    ]
