# Generated by Django 4.2.4 on 2024-02-09 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0077_courses_image_1_courses_image_2_courses_image_3_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="studentsmodel",
            name="image",
        ),
    ]
