# Generated by Django 4.2.4 on 2024-02-09 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0078_remove_studentsmodel_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="studentsmodel",
            name="image",
            field=models.ImageField(
                blank=True,
                default="default-student.png",
                null=True,
                upload_to="student-images/",
            ),
        ),
    ]
