from django.urls import path
from myapp import views

urlpatterns = [
    path("login/", views.loginPage, name="login"),
    path("logout/", views.logoutPage, name="logout"),
    path("", views.index, name="home"),
    path(
        "studentregister/<int:user_id>/",
        views.studentRegisterForm,
        name="student-register",
    ),
    path("studentsignup/", views.studentSignup, name="studentsignup"),
    path("studentdetails/<int:pk>/", views.studentDetails, name="studentdetails"),
    path("deletestudent/<int:pk>/", views.deleteStudent, name="delete"),
    path("editstudent/<int:pk>/", views.editStudent, name="edit"),
    path("addcourse/", views.addCourse, name="addcourse"),
    path("coursedetails/<int:pk>/", views.courseDetails, name="coursedetails"),
    path("deletecourse/<int:pk>/", views.courseDelete, name="delete-course"),
    path("updatecourse/<int:pk>/", views.courseUpdate, name="update-course"),
    path("student-tab/", views.studentTab, name="student-tab"),
    path("course-tab/", views.courseTab, name="course-tab"),
    path("contact-tab/", views.contactTab, name="contact"),
    path("about-tab/", views.aboutTab, name="about"),
    path("enquiry-tab/", views.enquiryTab, name="enquiry"),
    path("fees-tab/", views.feesTab, name="feestab"),
    path("servicesform/", views.services_form, name="servicesform"),
    path("rulesregulation/", views.rules_and_regulations, name="rulesregulation"),
    path("faculties/", views.faculties, name="faculties"),
    path("examreport/<int:pk>", views.examReport, name="examreport"),
    path("updateexamreport/<int:pk>/", views.editExamReport, name="updateexamreport"),
    path("sidebar/", views.sidebarmenu, name="sidebar"),
    path(
        "loggedin-students-details/",
        views.loggedin_student_details,
        name="loggedin-students-details",
    ),
    path(
        "studentlist_inside_studenttab/",
        views.studentlist_inside_studenttab,
        name="studentlist_inside_studenttab",
    ),
    path(
        "courselist_inside_coursetab/",
        views.courselist_inside_coursetab,
        name="courselist_inside_coursetab",
    ),
    path(
        "enquiries_inside_enquirytab/",
        views.enquiries_inside_enquirytab,
        name="enquiries_inside_enquirytab",
    ),
    path("syllabus/<int:pk>/", views.DownloadSyllabus, name="syllabusdownload"),
    path("download-pdf/<int:pk>/", views.download_pdf, name="download-pdf"),
    path("remarks/<int:pk>/", views.StudentRemark, name="remarks"),
    path("addenquiry", views.addenquiry, name="addenquiry"),
    path("payment_history/<int:pk>/", views.payment_history, name="payment_history"),
    path("add_installment/<int:pk>/", views.add_installment, name="add_installment"),
    path("cancel_admission/<int:pk>/", views.cancel_admission, name="cancel_admission"),
    path("search/", views.search_students, name="search_students"),
    path("searchcourse/", views.search_courses, name="search_courses"),
    path("print_exam_reports/", views.print_exam_reports, name="print_exam_reports"),
]
